"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _Operation:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _OperationEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Operation.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    SUCCESS: _Operation.ValueType  # 0
    FAILURE: _Operation.ValueType  # 1

class Operation(_Operation, metaclass=_OperationEnumTypeWrapper): ...

SUCCESS: Operation.ValueType  # 0
FAILURE: Operation.ValueType  # 1
global___Operation = Operation

@typing.final
class Post(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    POST_ID_FIELD_NUMBER: builtins.int
    AUTHOR_FIELD_NUMBER: builtins.int
    TITLE_FIELD_NUMBER: builtins.int
    CONTENT_FIELD_NUMBER: builtins.int
    TIMESTAMP_FIELD_NUMBER: builtins.int
    LIKES_FIELD_NUMBER: builtins.int
    post_id: builtins.str
    author: builtins.str
    title: builtins.str
    content: builtins.str
    timestamp: builtins.str
    @property
    def likes(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        post_id: builtins.str = ...,
        author: builtins.str = ...,
        title: builtins.str = ...,
        content: builtins.str = ...,
        timestamp: builtins.str = ...,
        likes: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["author", b"author", "content", b"content", "likes", b"likes", "post_id", b"post_id", "timestamp", b"timestamp", "title", b"title"]) -> None: ...

global___Post = Post

@typing.final
class Comment(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    POST_ID_FIELD_NUMBER: builtins.int
    EMAIL_FIELD_NUMBER: builtins.int
    TEXT_FIELD_NUMBER: builtins.int
    TIMESTAMP_FIELD_NUMBER: builtins.int
    post_id: builtins.str
    email: builtins.str
    text: builtins.str
    timestamp: builtins.str
    def __init__(
        self,
        *,
        post_id: builtins.str = ...,
        email: builtins.str = ...,
        text: builtins.str = ...,
        timestamp: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["email", b"email", "post_id", b"post_id", "text", b"text", "timestamp", b"timestamp"]) -> None: ...

global___Comment = Comment

@typing.final
class Notification(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TYPE_FIELD_NUMBER: builtins.int
    FROM_FIELD_NUMBER: builtins.int
    POST_ID_FIELD_NUMBER: builtins.int
    TITLE_FIELD_NUMBER: builtins.int
    TIMESTAMP_FIELD_NUMBER: builtins.int
    type: builtins.str
    post_id: builtins.str
    title: builtins.str
    timestamp: builtins.str
    def __init__(
        self,
        *,
        type: builtins.str = ...,
        post_id: builtins.str = ...,
        title: builtins.str = ...,
        timestamp: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["from", b"from", "post_id", b"post_id", "timestamp", b"timestamp", "title", b"title", "type", b"type"]) -> None: ...

global___Notification = Notification

@typing.final
class Request(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INFO_FIELD_NUMBER: builtins.int
    TERM_FIELD_NUMBER: builtins.int
    CANDIDATEID_FIELD_NUMBER: builtins.int
    LASTLOGINDEX_FIELD_NUMBER: builtins.int
    LASTLOGTERM_FIELD_NUMBER: builtins.int
    ENTRIES_FIELD_NUMBER: builtins.int
    LEADERCOMMIT_FIELD_NUMBER: builtins.int
    LEADERID_FIELD_NUMBER: builtins.int
    PREVLOGINDEX_FIELD_NUMBER: builtins.int
    PREVLOGTERM_FIELD_NUMBER: builtins.int
    term: builtins.int
    """For Raft RPCs
    Current term
    """
    candidateId: builtins.str
    """Candidate requesting vote"""
    lastLogIndex: builtins.int
    lastLogTerm: builtins.int
    leaderCommit: builtins.int
    """Leader's commitIndex"""
    leaderId: builtins.str
    """Leader's ID"""
    prevLogIndex: builtins.int
    prevLogTerm: builtins.int
    @property
    def info(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """For blog operations, 'info' holds strings like
          - "username", "password", "title", "content", etc.
        """

    @property
    def entries(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___RaftLogEntry]:
        """For AppendEntries
        Log entries to replicate
        """

    def __init__(
        self,
        *,
        info: collections.abc.Iterable[builtins.str] | None = ...,
        term: builtins.int = ...,
        candidateId: builtins.str = ...,
        lastLogIndex: builtins.int = ...,
        lastLogTerm: builtins.int = ...,
        entries: collections.abc.Iterable[global___RaftLogEntry] | None = ...,
        leaderCommit: builtins.int = ...,
        leaderId: builtins.str = ...,
        prevLogIndex: builtins.int = ...,
        prevLogTerm: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["candidateId", b"candidateId", "entries", b"entries", "info", b"info", "lastLogIndex", b"lastLogIndex", "lastLogTerm", b"lastLogTerm", "leaderCommit", b"leaderCommit", "leaderId", b"leaderId", "prevLogIndex", b"prevLogIndex", "prevLogTerm", b"prevLogTerm", "term", b"term"]) -> None: ...

global___Request = Request

@typing.final
class Response(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OPERATION_FIELD_NUMBER: builtins.int
    INFO_FIELD_NUMBER: builtins.int
    POSTS_FIELD_NUMBER: builtins.int
    NOTIFICATIONS_FIELD_NUMBER: builtins.int
    VOTEGRANTED_FIELD_NUMBER: builtins.int
    TERM_FIELD_NUMBER: builtins.int
    SUCCESS_FIELD_NUMBER: builtins.int
    operation: builtins.int
    """For blog operations
    SUCCESS = 0, FAILURE = 1
    """
    voteGranted: builtins.bool
    """For Raft RPCs
    True if candidate received vote
    """
    term: builtins.int
    """CurrentTerm, for leader/candidate to update itself"""
    success: builtins.bool
    """For AppendEntries success/failure"""
    @property
    def info(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """any extra string data"""

    @property
    def posts(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Post]:
        """For post listing operations"""

    @property
    def notifications(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Notification]:
        """For notification retrieval"""

    def __init__(
        self,
        *,
        operation: builtins.int = ...,
        info: collections.abc.Iterable[builtins.str] | None = ...,
        posts: collections.abc.Iterable[global___Post] | None = ...,
        notifications: collections.abc.Iterable[global___Notification] | None = ...,
        voteGranted: builtins.bool = ...,
        term: builtins.int = ...,
        success: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["info", b"info", "notifications", b"notifications", "operation", b"operation", "posts", b"posts", "success", b"success", "term", b"term", "voteGranted", b"voteGranted"]) -> None: ...

global___Response = Response

@typing.final
class RaftLogEntry(google.protobuf.message.Message):
    """A Raft log entry"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TERM_FIELD_NUMBER: builtins.int
    OPERATION_FIELD_NUMBER: builtins.int
    PARAMS_FIELD_NUMBER: builtins.int
    term: builtins.int
    """term of the entry"""
    operation: builtins.str
    """e.g. "SUBSCRIBE", "CREATE_POST", ..."""
    @property
    def params(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """parameters for that operation"""

    def __init__(
        self,
        *,
        term: builtins.int = ...,
        operation: builtins.str = ...,
        params: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["operation", b"operation", "params", b"params", "term", b"term"]) -> None: ...

global___RaftLogEntry = RaftLogEntry
